apiVersion: v1
kind: ConfigMap
metadata:
  name: flux-runtime-info
  namespace: flux-system
  labels:
    toolkit.fluxcd.io/runtime: "true"
    reconcile.fluxcd.io/watch: Enabled
  annotations:
    kustomize.toolkit.fluxcd.io/ssa: "Merge"
data:
  ARTIFACT_TAG: latest-stable
  ENVIRONMENT: production
  CLUSTER_NAME: prod-eu-1
  CLUSTER_DOMAIN: prodeu1.example.com
  ARTIFACT_SUBJECT_WORKFLOW: release-artifact
  ARTIFACT_SUBJECT_GIT_REF: refs/tags/.*
